# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pb.rpc_update_ticket_prices_pb2 as rpc__update__ticket__prices__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rpc_update_ticket_prices_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrivatePremierLeagueBookingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateTicketPrices = channel.unary_unary(
                '/private_pb.PrivatePremierLeagueBooking/UpdateTicketPrices',
                request_serializer=rpc__update__ticket__prices__pb2.UpdateTicketPricesRequest.SerializeToString,
                response_deserializer=rpc__update__ticket__prices__pb2.UpdateTicketPricesResponse.FromString,
                _registered_method=True)


class PrivatePremierLeagueBookingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateTicketPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrivatePremierLeagueBookingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateTicketPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTicketPrices,
                    request_deserializer=rpc__update__ticket__prices__pb2.UpdateTicketPricesRequest.FromString,
                    response_serializer=rpc__update__ticket__prices__pb2.UpdateTicketPricesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'private_pb.PrivatePremierLeagueBooking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('private_pb.PrivatePremierLeagueBooking', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrivatePremierLeagueBooking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateTicketPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/private_pb.PrivatePremierLeagueBooking/UpdateTicketPrices',
            rpc__update__ticket__prices__pb2.UpdateTicketPricesRequest.SerializeToString,
            rpc__update__ticket__prices__pb2.UpdateTicketPricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
