// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: additional_fees.sql

package db

import (
	"context"
)

const getTotalFeesByID = `-- name: GetTotalFeesByID :one
SELECT id, 
     CAST(
        (service_fee +
         vat_fee +
         payment_processing_fee +
         delivery_fee +
         vip_fee +
         specific_event_fee) AS NUMERIC
    ) AS total_fees
FROM additional_fees
WHERE id = $1
LIMIT 1
`

type GetTotalFeesByIDRow struct {
	ID        int32  `json:"id"`
	TotalFees string `json:"total_fees"`
}

func (q *Queries) GetTotalFeesByID(ctx context.Context, id int32) (GetTotalFeesByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTotalFeesByID, id)
	var i GetTotalFeesByIDRow
	err := row.Scan(&i.ID, &i.TotalFees)
	return i, err
}
