CREATE TABLE email_verification_tokens(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL,
    "token" varchar(32) NOT NULL
);
 
ALTER TABLE "email_verification_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");