// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: private_proto/private_service_plminibooking.proto

package private_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrivatePremierLeagueBooking_UpdateTicketPrices_FullMethodName = "/private_pb.PrivatePremierLeagueBooking/UpdateTicketPrices"
)

// PrivatePremierLeagueBookingClient is the client API for PrivatePremierLeagueBooking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivatePremierLeagueBookingClient interface {
	UpdateTicketPrices(ctx context.Context, in *UpdateTicketPricesRequest, opts ...grpc.CallOption) (*UpdateTicketPricesResponse, error)
}

type privatePremierLeagueBookingClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivatePremierLeagueBookingClient(cc grpc.ClientConnInterface) PrivatePremierLeagueBookingClient {
	return &privatePremierLeagueBookingClient{cc}
}

func (c *privatePremierLeagueBookingClient) UpdateTicketPrices(ctx context.Context, in *UpdateTicketPricesRequest, opts ...grpc.CallOption) (*UpdateTicketPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTicketPricesResponse)
	err := c.cc.Invoke(ctx, PrivatePremierLeagueBooking_UpdateTicketPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivatePremierLeagueBookingServer is the server API for PrivatePremierLeagueBooking service.
// All implementations must embed UnimplementedPrivatePremierLeagueBookingServer
// for forward compatibility.
type PrivatePremierLeagueBookingServer interface {
	UpdateTicketPrices(context.Context, *UpdateTicketPricesRequest) (*UpdateTicketPricesResponse, error)
	mustEmbedUnimplementedPrivatePremierLeagueBookingServer()
}

// UnimplementedPrivatePremierLeagueBookingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivatePremierLeagueBookingServer struct{}

func (UnimplementedPrivatePremierLeagueBookingServer) UpdateTicketPrices(context.Context, *UpdateTicketPricesRequest) (*UpdateTicketPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTicketPrices not implemented")
}
func (UnimplementedPrivatePremierLeagueBookingServer) mustEmbedUnimplementedPrivatePremierLeagueBookingServer() {
}
func (UnimplementedPrivatePremierLeagueBookingServer) testEmbeddedByValue() {}

// UnsafePrivatePremierLeagueBookingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivatePremierLeagueBookingServer will
// result in compilation errors.
type UnsafePrivatePremierLeagueBookingServer interface {
	mustEmbedUnimplementedPrivatePremierLeagueBookingServer()
}

func RegisterPrivatePremierLeagueBookingServer(s grpc.ServiceRegistrar, srv PrivatePremierLeagueBookingServer) {
	// If the following call pancis, it indicates UnimplementedPrivatePremierLeagueBookingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivatePremierLeagueBooking_ServiceDesc, srv)
}

func _PrivatePremierLeagueBooking_UpdateTicketPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivatePremierLeagueBookingServer).UpdateTicketPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivatePremierLeagueBooking_UpdateTicketPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivatePremierLeagueBookingServer).UpdateTicketPrices(ctx, req.(*UpdateTicketPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivatePremierLeagueBooking_ServiceDesc is the grpc.ServiceDesc for PrivatePremierLeagueBooking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivatePremierLeagueBooking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "private_pb.PrivatePremierLeagueBooking",
	HandlerType: (*PrivatePremierLeagueBookingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTicketPrices",
			Handler:    _PrivatePremierLeagueBooking_UpdateTicketPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "private_proto/private_service_plminibooking.proto",
}
