// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: private_proto/rpc_update_ticket_prices.proto

package private_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateTicketPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       int32                  `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketPricesRequest) Reset() {
	*x = UpdateTicketPricesRequest{}
	mi := &file_private_proto_rpc_update_ticket_prices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketPricesRequest) ProtoMessage() {}

func (x *UpdateTicketPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_proto_rpc_update_ticket_prices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketPricesRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketPricesRequest) Descriptor() ([]byte, []int) {
	return file_private_proto_rpc_update_ticket_prices_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateTicketPricesRequest) GetMatchId() int32 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

type UpdateTicketPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketPricesResponse) Reset() {
	*x = UpdateTicketPricesResponse{}
	mi := &file_private_proto_rpc_update_ticket_prices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketPricesResponse) ProtoMessage() {}

func (x *UpdateTicketPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_proto_rpc_update_ticket_prices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketPricesResponse.ProtoReflect.Descriptor instead.
func (*UpdateTicketPricesResponse) Descriptor() ([]byte, []int) {
	return file_private_proto_rpc_update_ticket_prices_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTicketPricesResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdateTicketPricesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_private_proto_rpc_update_ticket_prices_proto protoreflect.FileDescriptor

var file_private_proto_rpc_update_ticket_prices_proto_rawDesc = string([]byte{
	0x0a, 0x2c, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x72, 0x70, 0x63, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x62, 0x22, 0x36, 0x0a, 0x19, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x64, 0x22, 0x4e, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x70, 0x6c, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f,
	0x67, 0x6f, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x31, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_private_proto_rpc_update_ticket_prices_proto_rawDescOnce sync.Once
	file_private_proto_rpc_update_ticket_prices_proto_rawDescData []byte
)

func file_private_proto_rpc_update_ticket_prices_proto_rawDescGZIP() []byte {
	file_private_proto_rpc_update_ticket_prices_proto_rawDescOnce.Do(func() {
		file_private_proto_rpc_update_ticket_prices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_private_proto_rpc_update_ticket_prices_proto_rawDesc), len(file_private_proto_rpc_update_ticket_prices_proto_rawDesc)))
	})
	return file_private_proto_rpc_update_ticket_prices_proto_rawDescData
}

var file_private_proto_rpc_update_ticket_prices_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_private_proto_rpc_update_ticket_prices_proto_goTypes = []any{
	(*UpdateTicketPricesRequest)(nil),  // 0: private_pb.UpdateTicketPricesRequest
	(*UpdateTicketPricesResponse)(nil), // 1: private_pb.UpdateTicketPricesResponse
}
var file_private_proto_rpc_update_ticket_prices_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_private_proto_rpc_update_ticket_prices_proto_init() }
func file_private_proto_rpc_update_ticket_prices_proto_init() {
	if File_private_proto_rpc_update_ticket_prices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_private_proto_rpc_update_ticket_prices_proto_rawDesc), len(file_private_proto_rpc_update_ticket_prices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_private_proto_rpc_update_ticket_prices_proto_goTypes,
		DependencyIndexes: file_private_proto_rpc_update_ticket_prices_proto_depIdxs,
		MessageInfos:      file_private_proto_rpc_update_ticket_prices_proto_msgTypes,
	}.Build()
	File_private_proto_rpc_update_ticket_prices_proto = out.File
	file_private_proto_rpc_update_ticket_prices_proto_goTypes = nil
	file_private_proto_rpc_update_ticket_prices_proto_depIdxs = nil
}
